<?php

declare(strict_types=1);

return [
    [
        'id' => 1,
        'name' => '北海道',
        'short_name' => '北海道',
        'hiragana_name' => 'ほっかいどう',
        'katakana_name' => 'ホッカイドウ',
        'english_name' => 'hokkaido',
        'region_name' => '北海道',
    ],
    [
        'id' => 2,
        'name' => '青森県',
        'short_name' => '青森',
        'hiragana_name' => 'あおもりけん',
        'katakana_name' => 'アオモリケン',
        'english_name' => 'aomori',
        'region_name' => '東北',
    ],
    [
        'id' => 3,
        'name' => '岩手県',
        'short_name' => '岩手',
        'hiragana_name' => 'いわてけん',
        'katakana_name' => 'イワテケン',
        'english_name' => 'iwate',
        'region_name' => '東北',
    ],
    [
        'id' => 4,
        'name' => '宮城県',
        'short_name' => '宮城',
        'hiragana_name' => 'みやぎけん',
        'katakana_name' => 'ミヤギケン',
        'english_name' => 'miyagi',
        'region_name' => '東北',
    ],
    [
        'id' => 5,
        'name' => '秋田県',
        'short_name' => '秋田',
        'hiragana_name' => 'あきたけん',
        'katakana_name' => 'アキタケン',
        'english_name' => 'akita',
        'region_name' => '東北',
    ],
    [
        'id' => 6,
        'name' => '山形県',
        'short_name' => '山形',
        'hiragana_name' => 'やまがたけん',
        'katakana_name' => 'ヤマガタケン',
        'english_name' => 'yamagata',
        'region_name' => '東北',
    ],
    [
        'id' => 7,
        'name' => '福島県',
        'short_name' => '福島',
        'hiragana_name' => 'ふくしまけん',
        'katakana_name' => 'フクシマケン',
        'english_name' => 'fukushima',
        'region_name' => '東北',
    ],
    [
        'id' => 8,
        'name' => '茨城県',
        'short_name' => '茨城',
        'hiragana_name' => 'いばらきけん',
        'katakana_name' => 'イバラキケン',
        'english_name' => 'ibaraki',
        'region_name' => '関東',
    ],
    [
        'id' => 9,
        'name' => '栃木県',
        'short_name' => '栃木',
        'hiragana_name' => 'とちぎけん',
        'katakana_name' => 'トチギケン',
        'english_name' => 'tochigi',
        'region_name' => '関東',
    ],
    [
        'id' => 10,
        'name' => '群馬県',
        'short_name' => '群馬',
        'hiragana_name' => 'ぐんまけん',
        'katakana_name' => 'グンマケン',
        'english_name' => 'gunma',
        'region_name' => '関東',
    ],
    [
        'id' => 11,
        'name' => '埼玉県',
        'short_name' => '埼玉',
        'hiragana_name' => 'さいたまけん',
        'katakana_name' => 'サイタマケン',
        'english_name' => 'saitama',
        'region_name' => '関東',
    ],
    [
        'id' => 12,
        'name' => '千葉県',
        'short_name' => '千葉',
        'hiragana_name' => 'ちばけん',
        'katakana_name' => 'チバケン',
        'english_name' => 'chiba',
        'region_name' => '関東',
    ],
    [
        'id' => 13,
        'name' => '東京都',
        'short_name' => '東京',
        'hiragana_name' => 'とうきょうと',
        'katakana_name' => 'トウキョウト',
        'english_name' => 'tokyo',
        'region_name' => '関東',
    ],
    [
        'id' => 14,
        'name' => '神奈川県',
        'short_name' => '神奈川',
        'hiragana_name' => 'かながわけん',
        'katakana_name' => 'カナガワケン',
        'english_name' => 'kanagawa',
        'region_name' => '関東',
    ],
    [
        'id' => 15,
        'name' => '新潟県',
        'short_name' => '新潟',
        'hiragana_name' => 'にいがたけん',
        'katakana_name' => 'ニイガタケン',
        'english_name' => 'niigata',
        'region_name' => '中部',
    ],
    [
        'id' => 16,
        'name' => '富山県',
        'short_name' => '富山',
        'hiragana_name' => 'とやまけん',
        'katakana_name' => 'トヤマケン',
        'english_name' => 'toyama',
        'region_name' => '中部',
    ],
    [
        'id' => 17,
        'name' => '石川県',
        'short_name' => '石川',
        'hiragana_name' => 'いしかわけん',
        'katakana_name' => 'イシカワケン',
        'english_name' => 'ishikawa',
        'region_name' => '中部',
    ],
    [
        'id' => 18,
        'name' => '福井県',
        'short_name' => '福井',
        'hiragana_name' => 'ふくいけん',
        'katakana_name' => 'フクイケン',
        'english_name' => 'fukui',
        'region_name' => '中部',
    ],
    [
        'id' => 19,
        'name' => '山梨県',
        'short_name' => '山梨',
        'hiragana_name' => 'やまなしけん',
        'katakana_name' => 'ヤマナシケン',
        'english_name' => 'yamanashi',
        'region_name' => '中部',
    ],
    [
        'id' => 20,
        'name' => '長野県',
        'short_name' => '長野',
        'hiragana_name' => 'ながのけん',
        'katakana_name' => 'ナガノケン',
        'english_name' => 'nagano',
        'region_name' => '中部',
    ],
    [
        'id' => 21,
        'name' => '岐阜県',
        'short_name' => '岐阜',
        'hiragana_name' => 'ぎふけん',
        'katakana_name' => 'ギフケン',
        'english_name' => 'gifu',
        'region_name' => '中部',
    ],
    [
        'id' => 22,
        'name' => '静岡県',
        'short_name' => '静岡',
        'hiragana_name' => 'しずおかけん',
        'katakana_name' => 'シズオカケン',
        'english_name' => 'shizuoka',
        'region_name' => '中部',
    ],
    [
        'id' => 23,
        'name' => '愛知県',
        'short_name' => '愛知',
        'hiragana_name' => 'あいちけん',
        'katakana_name' => 'アイチケン',
        'english_name' => 'aichi',
        'region_name' => '中部',
    ],
    [
        'id' => 24,
        'name' => '三重県',
        'short_name' => '三重',
        'hiragana_name' => 'みえけん',
        'katakana_name' => 'ミエケン',
        'english_name' => 'mie',
        'region_name' => '関西',
    ],
    [
        'id' => 25,
        'name' => '滋賀県',
        'short_name' => '滋賀',
        'hiragana_name' => 'しがけん',
        'katakana_name' => 'シガケン',
        'english_name' => 'shiga',
        'region_name' => '関西',
    ],
    [
        'id' => 26,
        'name' => '京都府',
        'short_name' => '京都',
        'hiragana_name' => 'きょうとふ',
        'katakana_name' => 'キョウトフ',
        'english_name' => 'kyoto',
        'region_name' => '関西',
    ],
    [
        'id' => 27,
        'name' => '大阪府',
        'short_name' => '大阪',
        'hiragana_name' => 'おおさかふ',
        'katakana_name' => 'オオサカフ',
        'english_name' => 'osaka',
        'region_name' => '関西',
    ],
    [
        'id' => 28,
        'name' => '兵庫県',
        'short_name' => '兵庫',
        'hiragana_name' => 'ひょうごけん',
        'katakana_name' => 'ヒョウゴケン',
        'english_name' => 'hyogo',
        'region_name' => '関西',
    ],
    [
        'id' => 29,
        'name' => '奈良県',
        'short_name' => '奈良',
        'hiragana_name' => 'ならけん',
        'katakana_name' => 'ナラケン',
        'english_name' => 'nara',
        'region_name' => '関西',
    ],
    [
        'id' => 30,
        'name' => '和歌山県',
        'short_name' => '和歌山',
        'hiragana_name' => 'わかやまけん',
        'katakana_name' => 'ワカヤマケン',
        'english_name' => 'wakayama',
        'region_name' => '関西',
    ],
    [
        'id' => 31,
        'name' => '鳥取県',
        'short_name' => '鳥取',
        'hiragana_name' => 'とっとりけん',
        'katakana_name' => 'トットリケン',
        'english_name' => 'tottori',
        'region_name' => '中国',
    ],
    [
        'id' => 32,
        'name' => '島根県',
        'short_name' => '島根',
        'hiragana_name' => 'しまねけん',
        'katakana_name' => 'シマネケン',
        'english_name' => 'shimane',
        'region_name' => '中国',
    ],
    [
        'id' => 33,
        'name' => '岡山県',
        'short_name' => '岡山',
        'hiragana_name' => 'おかやまけん',
        'katakana_name' => 'オカヤマケン',
        'english_name' => 'okayama',
        'region_name' => '中国',
    ],
    [
        'id' => 34,
        'name' => '広島県',
        'short_name' => '広島',
        'hiragana_name' => 'ひろしまけん',
        'katakana_name' => 'ヒロシマケン',
        'english_name' => 'hiroshima',
        'region_name' => '中国',
    ],
    [
        'id' => 35,
        'name' => '山口県',
        'short_name' => '山口',
        'hiragana_name' => 'やまぐちけん',
        'katakana_name' => 'ヤマグチケン',
        'english_name' => 'yamaguchi',
        'region_name' => '中国',
    ],
    [
        'id' => 36,
        'name' => '徳島県',
        'short_name' => '徳島',
        'hiragana_name' => 'とくしまけん',
        'katakana_name' => 'トクシマケン',
        'english_name' => 'tokushima',
        'region_name' => '四国',
    ],
    [
        'id' => 37,
        'name' => '香川県',
        'short_name' => '香川',
        'hiragana_name' => 'かがわけん',
        'katakana_name' => 'カガワケン',
        'english_name' => 'kagawa',
        'region_name' => '四国',
    ],
    [
        'id' => 38,
        'name' => '愛媛県',
        'short_name' => '愛媛',
        'hiragana_name' => 'えひめけん',
        'katakana_name' => 'エヒメケン',
        'english_name' => 'ehime',
        'region_name' => '四国',
    ],
    [
        'id' => 39,
        'name' => '高知県',
        'short_name' => '高知',
        'hiragana_name' => 'こうちけん',
        'katakana_name' => 'コウチケン',
        'english_name' => 'kochi',
        'region_name' => '四国',
    ],
    [
        'id' => 40,
        'name' => '福岡県',
        'short_name' => '福岡',
        'hiragana_name' => 'ふくおかけん',
        'katakana_name' => 'フクオカケン',
        'english_name' => 'fukuoka',
        'region_name' => '九州',
    ],
    [
        'id' => 41,
        'name' => '佐賀県',
        'short_name' => '佐賀',
        'hiragana_name' => 'さがけん',
        'katakana_name' => 'サガケン',
        'english_name' => 'saga',
        'region_name' => '九州',
    ],
    [
        'id' => 42,
        'name' => '長崎県',
        'short_name' => '長崎',
        'hiragana_name' => 'ながさきけん',
        'katakana_name' => 'ナガサキケン',
        'english_name' => 'nagasaki',
        'region_name' => '九州',
    ],
    [
        'id' => 43,
        'name' => '熊本県',
        'short_name' => '熊本',
        'hiragana_name' => 'くまもとけん',
        'katakana_name' => 'クマモトケン',
        'english_name' => 'kumamoto',
        'region_name' => '九州',
    ],
    [
        'id' => 44,
        'name' => '大分県',
        'short_name' => '大分',
        'hiragana_name' => 'おおいたけん',
        'katakana_name' => 'オオイタケン',
        'english_name' => 'oita',
        'region_name' => '九州',
    ],
    [
        'id' => 45,
        'name' => '宮崎県',
        'short_name' => '宮崎',
        'hiragana_name' => 'みやざきけん',
        'katakana_name' => 'ミヤザキケン',
        'english_name' => 'miyazaki',
        'region_name' => '九州',
    ],
    [
        'id' => 46,
        'name' => '鹿児島県',
        'short_name' => '鹿児島',
        'hiragana_name' => 'かごしまけん',
        'katakana_name' => 'カゴシマケン',
        'english_name' => 'kagoshima',
        'region_name' => '九州',
    ],
    [
        'id' => 47,
        'name' => '沖縄県',
        'short_name' => '沖縄',
        'hiragana_name' => 'おきなわけん',
        'katakana_name' => 'オキナワケン',
        'english_name' => 'okinawa',
        'region_name' => '九州',
    ],
];
